### PR TITLE
Initial commit for adding a discount to the product-details.html pages.

### PR DESCRIPTION
**Pull request by JmmonJeremy**
Created a new branch jts--add-discount-to-detail-pages-feature and added the discount in bold and red color to the product-details.html pages on that page I added the discount to line 19. Then on productDetails.js line 66 I subtracted the products ListPrice from its SuggestedRetailPrice to show the amount of the discount for the product. Then in style.css lines 307 to 311 I added styling to make it red and underlined. The feature is working great. I pushed the branch and put in a pull request.

- [x] Test to make sure that the discount shows on the product-details.html page when you go to it for different products.
- [x] Confirm that the discount number is correct.
- [x] Make sure that the discount notification looks good.

### CODE REVIEW

**Comment by Wmsmckay** [comment]
The code and the functionality of this branch work great, but I don't understand what the discount is showing. In the product page it shows the price, and then it says "Discount of $X!". Is that X dollars the amount that the product is discounted, and is the price above that the original price? 

Screen Shot 2022-05-09 at 10 46 06 AM

I think that doing something similar to amazon where the original price is crossed out and the price the user will pay is displayed more boldly.

Screen Shot 2022-05-09 at 10 50 27 AM

**Comment by Wmsmckay** [comment]
I went through and resolved the merge conflicts between this branch and the current main.

**Comment by JmmonJeremy** [comment]
I made some changes to try and make it clearer for the user. Let me know what you think.

**Comment by Wmsmckay** [comment]
That looks awesome! I love the look of it a lot more. Nice work

**Pull request merged**
