### PR TITLE
Mw  product list sort

### PR DESCRIPTION
**Pull request by Wmsmckay**
This pull request creates a slider on the product listing page. The slider allows the user to select if they want to view the products in alphabetical order or by price ascending.

- [x] Go to the product listing page for any of the products
- [x] check to make sure that all of the results are in alphabetical order
- [x] click on the slider and make sure that the products change to show the lowest price first with the highest price last
- [x] click on the slider again and make sure the the results change back to alphabetical

### CODE REVIEW

**Comment by Wmsmckay** [comment]
The majority of the files changes were from the formatting. The only code changes are in:
- js/productListing.js
- product-listing/index.html
- js/productList.js

**Comment by Wmsmckay** [comment]
I fixed the merge conflicts so it is ready to be merged again

**Comment by JmmonJeremy** [comment]
I trialed all of the pages and it works on each page. It was unclear to me what was being sorted on the name function at first. At first I thought it wasn't working because the brand names were not in alphabetical order. Then the fact that numbers are sorted before "a" was confusing to me at first. I eventually figured out how it was being sorted, but I would suggest sorting by brand name first and then if they have multiple products in the brand name sorting those. I think that would be less confusing for a user because the brand name is at the top and the first thing you see.

**Comment by Wmsmckay** [comment]
I didn't want to sort by the brand name because there are multiple of the same brand and it might be confusing looking. I was thinking about adding another button that does price, product name and brand name, but that is outside the scope of the project. I'll change the name to 'product name' so it is a little more descriptive to the user. What do you think?

**Comment by JmmonJeremy** [comment]
> I didn't want to sort by the brand name because there are multiple of the same brand and it might be confusing looking. I was thinking about adding another button that does price, product name and brand name, but that is outside the scope of the project. I'll change the name to 'product name' so it is a little more descriptive to the user. What do you think?

That would help with the clarity.

**Comment by JmmonJeremy** [comment]
I looked at it with Product Name as an option for the sort. This is clearer and I think it works. I am going to merge this.

**Pull request merged**
