### PR TITLE
Mw  breadcrumbs

### PR DESCRIPTION
**Pull request by Wmsmckay**
This PR is a branch made from the previous PR @ #39 . Please ensure that request is completed first.
This adds in breadcrumbs in the product details pages. On the main product list page, it will show breadcumbs with the homepage, and the product category (including how many total products of that type there are). The product details page will show the user the home page and the category page for the product they are viewing.

- [x] ensure that the link from the product listing page takes you to the home page and the other one doesn't take you anywhere
- [x] ensure that the links in the product details page takes you to the homepage, and the category page for the product you are viewing (eg, a tent's page will take you back to the tensts.

### CODE REVIEW

**Comment by Wmsmckay** [comment]
This branch's merge conflicts have been resolved

**Comment by JmmonJeremy** [comment]
I tested it and the links work. I believe there is a typo in the code on the product category page. It has -> in front of the number of the products. If it is not a typo I think it should be changed. It is confusing. Maybe ":" between tents and the number would work with "available" after the number to help the user be clear what the number represents. After looking at the card it says to have "items" after the number.

**Comment by Wmsmckay** [comment]
I agree that is doesn't look great. I wasn't sure how to do it well. I put some changes in to make it look better. Let me know what you think
Screen Shot 2022-05-16 at 11 05 00 AM
!

**Comment by JmmonJeremy** [comment]
I looked at the updated version and it looks much better. What the number represents is now clear. I am merging this to main now.

**Pull request merged**
