### PR TITLE
Created another branch for L08 Team7 with add ins from the teacher's version (jts--team7 branch).…

### PR DESCRIPTION
**Pull request by JmmonJeremy**
… This is a second option for this feature.

### CODE REVIEW

**Comment by JmmonJeremy** [comment]
OPTION 2 (Incorporating things from the teacher's solution)

Tests:

- [ ] Submit Form with invalid card number and invalid card date & both errors should show at the top.
- [ ] Submit Form correctly and it should take you to a confirmation page and remove the items from the cart
- [ ] Order from the product pages & a message should 
- [ ] Add your name to the version you would like our team to go with in this comment section
I vote for this version jts--team7 branch: McKay
I vote for the other version cp--Team7 branch:
I vote for a third option of making a third branch with parts of both branches: Jeremy

**Comment by Wmsmckay** [comment]
Besides the banners, are there any functional differences between the branches?

**Comment by JmmonJeremy** [comment]
> Besides the banners, are there any functional differences between the branches?

They function the same. The way the functionality is accomplished is a little different. This branch has the insertion of the comment within the alertMessage function. The other branch with the way we were doing it does the insertion of the alert in the place where the alertMessage is called. Also this one uses a for in loop to get the error messages and seems like a lot less code to accomplish the same thing I did in the other branch, but the other branch puts more information about the error in the alert message.

**Comment by JmmonJeremy** [comment]
We've decided to merge this branch. It works great and there are no merge conflicts. I am proceeding with merging it to the main branch.

**Pull request merged**
