### PR TITLE
initial commit for L08 Team 7 (cp--Team7 branch)

### PR DESCRIPTION
**Pull request by CherellePayne**
still working on alert message functioning
Co-authored-by: JmmonJeremy <JmmonJeremy@users.noreply.github.com>
Co-authored-by: McKay Williams <Wmsmckay@users.noreply.github.com>
Co-authored-by: Tony Edson Torres de Morais <tonylds1@gmail.com>
Co-authored-by: LawrenceYamete <LawrenceYamete@users.noreply.github.com>

### CODE REVIEW

**Comment by CherellePayne** [comment]
Until the message errors are fixed don't merge this branch.

**Comment by JmmonJeremy** [comment]
OPTION 1 (Got our version we did together working)

Tests:

- [x] Submit Form with invalid card number and invalid card date & both errors should show at the top.
- [x] Submit Form correctly and it should take you to a confirmation page and remove the items from the cart
- [x] Order from the product pages & a message should 
- [x] Add your name to the version you would like our team to go with in this comment section
I vote for this version cp--Team7 branch: 
I vote for the other version jts--team7 branch: Cherelle 
I vote for a third option of making a third branch with parts of both branches: Jeremy

**Review by CherellePayne — COMMENTED** [review]
This looks great Jeremy. 

I like 'removeAllAlerts' addition

**Comment by JmmonJeremy** [comment]
We voted to merge the other branch, so I am closing this merge request.

**Pull request closed without merging**
